image: node:12.10.0 # change to match your node version

stages:
  - build
  - release
cache:
  paths:
    - node_modules/

before_script:
  - npm install -g yarn
  - yarn

build:
  stage: build
  script:
    - CI=true yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^ci-/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^master/'
      when: always
  script:
  - mv public $CI_PROJECT_NAME.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA
  artifacts:
    paths:
      - $CI_PROJECT_NAME.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA
