image: node:12.10.0 # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g yarn
  - yarn

build:
  stage: build
  script:
    - CI=true yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory

release:
  stage: release
  only: branches
  script:
  - mv public $CI_PROJECT_NAME.$CI_COMMIT_SHORT_SHA
  release:
    name: $CI_PROJECT_NAME release $CI_COMMIT_SHORT_SHA
    assets:
    - name: $CI_PROJECT_NAME.$CI_COMMIT_SHORT_SHA.zip
      path: $CI_PROJECT_NAME.$CI_COMMIT_SHORT_SHA
